#!/bin/bash
# =============================================================================
# setup_env.sh - Fish Finder EC2 Worker Setup Script
# =============================================================================
#
# Run this script on a fresh EC2 Ubuntu instance AFTER SCP-ing the package:
#
#   STEP 1 (local): bash package_worker.sh
#   STEP 2 (local): scp -i Dor-key.pem fish_worker.tar.gz setup_env.sh ubuntu@<EC2_IP>:~/
#   STEP 3 (EC2):   bash setup_env.sh <SQS_URL> <SNS_ARN> [AWS_REGION]
#
# The script is idempotent - safe to re-run after updates.
# =============================================================================

set -e  # Exit immediately on any error

# --- 0. ARGUMENT PARSING & VALIDATION ---
SQS_URL="${1}"
SNS_ARN="${2}"
AWS_REGION="${3:-eu-north-1}"   # Default to the region used in infrastructure/

if [ -z "$SQS_URL" ] || [ -z "$SNS_ARN" ]; then
    echo "❌ ERROR: Missing required arguments."
    echo ""
    echo "Usage:   bash setup_env.sh <SQS_QUEUE_URL> <SNS_TOPIC_ARN> [AWS_REGION]"
    echo "Example: bash setup_env.sh https://sqs.eu-north-1... arn:aws:sns:... eu-north-1"
    echo ""
    echo "Find these values in your Terraform outputs after 'terraform apply'."
    exit 1
fi

WORKER_DIR="$HOME/fish-finder-worker"

echo ""
echo "=============================================="
echo "  Fish Finder Worker - EC2 Setup Script"
echo "=============================================="
echo "  SQS URL:    $SQS_URL"
echo "  SNS ARN:    $SNS_ARN"
echo "  AWS Region: $AWS_REGION"
echo "  Worker Dir: $WORKER_DIR"
echo "=============================================="
echo ""

# --- 1. SWAP FILE ---
# t3.micro has 1GB RAM. PyTorch needs ~1.5GB at load time, so swap is essential.
echo "[1/7] Setting up swap file..."
if [ -f /swapfile ]; then
    echo "      ✅ Swap file already exists, skipping."
else
    sudo fallocate -l 2G /swapfile
    sudo chmod 600 /swapfile
    sudo mkswap /swapfile
    sudo swapon /swapfile
    # Persist swap across reboots by adding to fstab (only if not already there)
    grep -q '/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
    echo "      ✅ 2GB swap file created and activated."
fi

# --- 2. SYSTEM PACKAGES ---
echo ""
echo "[2/7] Installing system packages..."
sudo apt-get update -q
sudo apt-get install -y -q python3-pip python3-venv
echo "      ✅ Python3, pip, venv installed."

# --- 3. EXTRACT WORKER PACKAGE ---
echo ""
echo "[3/7] Extracting worker package (fish_worker.tar.gz)..."
if [ ! -f "$HOME/fish_worker.tar.gz" ]; then
    echo "      ❌ ERROR: fish_worker.tar.gz not found in $HOME"
    echo "         Run package_worker.sh locally first, then SCP the result."
    exit 1
fi

mkdir -p "$WORKER_DIR"
tar -xzf "$HOME/fish_worker.tar.gz" -C "$WORKER_DIR"
echo "      ✅ Files extracted to $WORKER_DIR"
echo "      Contents:"
ls -lh "$WORKER_DIR/scripts/" 2>/dev/null && ls -lh "$WORKER_DIR/models/" 2>/dev/null || true

# --- 4. PYTHON VIRTUAL ENVIRONMENT ---
echo ""
echo "[4/7] Creating Python virtual environment..."
python3 -m venv "$WORKER_DIR/venv"
echo "      ✅ Virtual environment created at $WORKER_DIR/venv"

# --- 5. PYTHON DEPENDENCIES ---
echo ""
echo "[5/7] Installing Python dependencies (this may take a few minutes)..."
# Activate venv for pip installs
"$WORKER_DIR/venv/bin/pip" install --upgrade pip -q
# CPU-only PyTorch: ~200MB vs ~800MB for GPU - much better for t3.micro
"$WORKER_DIR/venv/bin/pip" install torch torchvision --index-url https://download.pytorch.org/whl/cpu -q
"$WORKER_DIR/venv/bin/pip" install boto3 Pillow -q
echo "      ✅ All Python packages installed."

# --- 6. ENVIRONMENT CONFIGURATION ---
echo ""
echo "[6/7] Writing environment configuration..."
# Store secrets/config in a .env file - systemd reads this via EnvironmentFile
# Do NOT put credentials in the service file itself (shows up in 'systemctl status')
cat > "$WORKER_DIR/.env" << EOF
# Fish Finder Worker - Environment Configuration
# Generated by setup_env.sh on $(date)
QUEUE_URL=$SQS_URL
SNS_ARN=$SNS_ARN
AWS_REGION=$AWS_REGION
EOF
chmod 600 "$WORKER_DIR/.env"   # Only the ubuntu user can read it
echo "      ✅ Configuration written to $WORKER_DIR/.env"

# --- 7. SYSTEMD SERVICE ---
# systemd manages the process lifecycle: auto-start on boot, restart on crash.
echo ""
echo "[7/7] Installing systemd service (fish-finder-worker)..."

sudo tee /etc/systemd/system/fish-finder-worker.service > /dev/null << EOF
[Unit]
Description=Fish Finder ML Worker (SQS -> S3 -> ML -> DynamoDB/SNS)
# Wait for network before starting - we need AWS access
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=ubuntu
# Scripts directory is where model_logic.py and fish_dictionary.py live
WorkingDirectory=$WORKER_DIR/scripts
# Load QUEUE_URL, SNS_ARN, AWS_REGION from the .env file
EnvironmentFile=$WORKER_DIR/.env
# Run ec2_worker.py using the venv's Python
ExecStart=$WORKER_DIR/venv/bin/python ec2_worker.py
# Restart automatically if it crashes (e.g. transient network error)
Restart=always
RestartSec=15
# Send logs to journald (view with: sudo journalctl -u fish-finder-worker -f)
StandardOutput=journal
StandardError=journal

[Install]
# Start this service when the system reaches the normal multi-user state
WantedBy=multi-user.target
EOF

# Apply the new service file and start the worker
sudo systemctl daemon-reload
sudo systemctl enable fish-finder-worker   # Auto-start on boot
sudo systemctl restart fish-finder-worker  # Start now (or restart if already running)

# Give it a moment to initialise before checking status
sleep 4

echo ""
echo "=============================================="
echo "✅ Setup complete! Checking service status..."
echo "=============================================="
sudo systemctl status fish-finder-worker --no-pager -l

echo ""
echo "=============================================="
echo "  Useful commands:"
echo "  View live logs:  sudo journalctl -u fish-finder-worker -f"
echo "  Stop worker:     sudo systemctl stop fish-finder-worker"
echo "  Restart worker:  sudo systemctl restart fish-finder-worker"
echo "=============================================="