#!/bin/bash
# =============================================================================
# setup_webapp.sh - Fish Finder Webapp Setup Script
#
# Run this on the webapp EC2 instance after SCP-ing the webapp/ directory:
#
#   STEP 1 (local): scp -i Dor-key.pem -r webapp/ ubuntu@<WEBAPP_IP>:~/
#   STEP 2 (EC2):   bash ~/webapp/setup_webapp.sh <COGNITO_POOL_ID> <COGNITO_CLIENT_ID> <S3_BUCKET> [REGION]
#
# All arguments come from 'terraform output' after 'terraform apply'.
# The script is idempotent - safe to re-run after code updates.
# =============================================================================

set -e

COGNITO_POOL_ID="${1}"
COGNITO_CLIENT_ID="${2}"
S3_BUCKET="${3}"
AWS_REGION="${4:-eu-north-1}"

if [ -z "$COGNITO_POOL_ID" ] || [ -z "$COGNITO_CLIENT_ID" ] || [ -z "$S3_BUCKET" ]; then
    echo "❌ Usage: bash setup_webapp.sh <COGNITO_POOL_ID> <COGNITO_CLIENT_ID> <S3_BUCKET> [AWS_REGION]"
    echo ""
    echo "Find these in Terraform outputs:"
    echo "  terraform output cognito_user_pool_id"
    echo "  terraform output cognito_webapp_client_id"
    echo "  terraform output uploads_bucket_name"
    exit 1
fi

WEBAPP_DIR="$HOME/webapp"

echo ""
echo "=========================================="
echo "  Fish Finder - Webapp Setup"
echo "=========================================="
echo "  Cognito Pool:   $COGNITO_POOL_ID"
echo "  Cognito Client: $COGNITO_CLIENT_ID"
echo "  S3 Bucket:      $S3_BUCKET"
echo "  AWS Region:     $AWS_REGION"
echo "=========================================="
echo ""

# --- 1. PYTHON VIRTUAL ENVIRONMENT ---
echo "[1/5] Creating Python virtual environment..."
python3 -m venv "$WEBAPP_DIR/venv"
"$WEBAPP_DIR/venv/bin/pip" install --upgrade pip -q
echo "      ✅ Virtual environment ready."

# --- 2. PYTHON DEPENDENCIES ---
echo ""
echo "[2/5] Installing Python dependencies..."
"$WEBAPP_DIR/venv/bin/pip" install \
    flask==3.0.3 flask-cors==4.0.1 \
    boto3==1.34.144 botocore==1.34.144 \
    python-jose[cryptography]==3.3.0 \
    requests==2.32.0 -q
echo "      ✅ Dependencies installed."

# --- 3. ENVIRONMENT CONFIGURATION ---
echo ""
echo "[3/5] Writing environment configuration..."
cat > "$WEBAPP_DIR/.env" << EOF
# Fish Finder Webapp - Environment Configuration
# Generated by setup_webapp.sh on $(date)
FF_AWS_REGION=$AWS_REGION
FF_S3_BUCKET=$S3_BUCKET
FF_COGNITO_POOL_ID=$COGNITO_POOL_ID
FF_COGNITO_CLIENT_ID=$COGNITO_CLIENT_ID
EOF
chmod 600 "$WEBAPP_DIR/.env"
echo "      ✅ Config written to $WEBAPP_DIR/.env"

# --- 4. SYSTEMD SERVICE ---
echo ""
echo "[4/5] Installing systemd service (fish-finder-webapp)..."

sudo tee /etc/systemd/system/fish-finder-webapp.service > /dev/null << EOF
[Unit]
Description=Fish Finder Web API
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=ubuntu
WorkingDirectory=$WEBAPP_DIR
EnvironmentFile=$WEBAPP_DIR/.env
ExecStart=$WEBAPP_DIR/venv/bin/python app.py
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable fish-finder-webapp
sudo systemctl restart fish-finder-webapp

sleep 3

# --- 5. VERIFY ---
echo ""
echo "[5/5] Verifying service status..."
sudo systemctl status fish-finder-webapp --no-pager -l

echo ""
echo "=========================================="
echo "✅ Webapp is running on port 5000"
echo "   Logs: sudo journalctl -u fish-finder-webapp -f"
echo "=========================================="
